import { createHmac } from 'node:crypto';
import {
  adminSigningBase,
  bodyDigest,
  isSafeActorRef,
  isSafeRequestId,
  verifyAdminSignature,
} from './admin-control-signature';
import { signingBase as websiteSigningBase } from '../website/intake-signature';

/**
 * The control plane's signing contract.
 *
 * This file is the SPECIFICATION the Central Admin backend implements, in its
 * own repository, without importing a line of this one. The fixed vector below
 * is therefore not an ordinary test: it is the thing both sides agree on, and
 * changing any byte of it breaks a system that is not in this codebase.
 *
 * Everything else here is a way for a forged or replayed request to be refused.
 */

/** A test fixture, not a secret: nothing real is reachable with it. */
const SECRET = 'admin-control-test-signing-secret-32-chars';

describe('admin control signing base', () => {
  it('binds the method, the path and the body — not just the body', () => {
    const rawBody = Buffer.from('{"name":"Pune Sales"}');
    const common = {
      timestamp: '1774000000',
      requestId: 'req-1',
      actorRef: 'admin-uid-1',
      rawBody,
    };

    const post = adminSigningBase({ ...common, method: 'POST', path: '/api/v1/x/teams' });
    const patch = adminSigningBase({ ...common, method: 'PATCH', path: '/api/v1/x/teams' });
    const other = adminSigningBase({ ...common, method: 'POST', path: '/api/v1/x/territories' });

    /*
     * The reason method and path are in the base at all. A signature over the
     * body alone lets a captured "create a team" be replayed as "create a
     * territory", or a GET be re-aimed at a destructive verb, and it would
     * verify perfectly.
     */
    expect(new Set([post, patch, other]).size).toBe(3);
  });

  it('upper-cases the method, so a caller cannot sign "post" and send "POST"', () => {
    const input = {
      path: '/api/v1/x',
      timestamp: '1774000000',
      requestId: 'req-1',
      actorRef: 'admin-1',
      rawBody: undefined,
    };

    expect(adminSigningBase({ ...input, method: 'post' })).toBe(
      adminSigningBase({ ...input, method: 'POST' }),
    );
  });

  it('hashes empty bytes for a body-less request', () => {
    // The SHA-256 of nothing at all. A GET has no body, and leaving the digest
    // out instead would make the number of fields vary with the request.
    expect(bodyDigest(undefined)).toBe(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    );
    expect(bodyDigest(Buffer.alloc(0))).toBe(bodyDigest(undefined));
  });

  it('cannot be forged by moving the delimiter into a value', () => {
    // The request id and actor reference are validated to a printable,
    // newline-free shape before they ever reach the base, which is what makes
    // a newline delimiter safe.
    expect(isSafeRequestId('req-1\nPOST')).toBe(false);
    expect(isSafeActorRef('admin\n/api/v1/x')).toBe(false);
    expect(isSafeRequestId('req with space')).toBe(false);
    expect(isSafeRequestId('req-1')).toBe(true);
    expect(isSafeActorRef('firebase:uid:abc123')).toBe(true);
  });

  it('is NOT the website contract', () => {
    /*
     * J1 is implemented by a deployed website backend. Widening its base to
     * share one with this would mean changing bytes a system outside this
     * repository produces, for the benefit of one that does not exist yet.
     *
     * This assertion exists so that a later attempt to "unify" them fails here
     * rather than in production.
     */
    const rawBody = Buffer.from('{"a":1}');

    expect(
      adminSigningBase({
        method: 'POST',
        path: '/api/v1/integrations/website/intake',
        timestamp: '1774000000',
        requestId: 'evt-1',
        actorRef: 'admin-1',
        rawBody,
      }),
    ).not.toBe(websiteSigningBase({ timestamp: '1774000000', eventId: 'evt-1', rawBody }));
  });
});

/**
 * THE CONTRACT TEST VECTOR.
 *
 * Every value below is fixed. The Central Admin backend must produce exactly
 * this signature from exactly these inputs, using nothing but HMAC-SHA256 and
 * the documented signing base — no shared library, no copied file.
 *
 * If this test is ever changed, the other side of the integration breaks.
 */
describe('contract test vector', () => {
  const VECTOR = {
    secret: SECRET,
    method: 'POST',
    path: '/api/v1/integrations/admin-control/teams',
    timestamp: '1774000000',
    requestId: 'cmd-0001',
    actorRef: 'firebase:uid:Zx9',
    body: '{"name":"Pune Sales"}',
  };

  const rawBody = Buffer.from(VECTOR.body, 'utf8');

  /*
   * Both constants below were computed INDEPENDENTLY, with Python's hashlib
   * and hmac, and agree with what Node produces here. That is what makes this
   * a cross-implementation contract rather than a recording of our own
   * output: a vector generated by the code it tests would pass just as
   * happily if the scheme were wrong.
   */
  const BODY_DIGEST = '10da1813c2d49072727eedcd6cb8bfda0c4e3e52c413b157420525c32373a525';
  const SIGNATURE =
    'sha256=49537950c70c451464d34526e67e871936c7917880fd0d9ade89cb52c417c246';

  it('produces the agreed body digest', () => {
    expect(bodyDigest(rawBody)).toBe(BODY_DIGEST);
  });

  it('produces the agreed signing base', () => {
    expect(
      adminSigningBase({
        method: VECTOR.method,
        path: VECTOR.path,
        timestamp: VECTOR.timestamp,
        requestId: VECTOR.requestId,
        actorRef: VECTOR.actorRef,
        rawBody,
      }),
    ).toBe(
      [
        'POST',
        '/api/v1/integrations/admin-control/teams',
        '1774000000',
        'cmd-0001',
        'firebase:uid:Zx9',
        BODY_DIGEST,
      ].join('\n'),
    );
  });

  it('produces the agreed signature header', () => {
    const signature = `sha256=${createHmac('sha256', VECTOR.secret)
      .update(
        adminSigningBase({
          method: VECTOR.method,
          path: VECTOR.path,
          timestamp: VECTOR.timestamp,
          requestId: VECTOR.requestId,
          actorRef: VECTOR.actorRef,
          rawBody,
        }),
      )
      .digest('hex')}`;

    // THE byte-for-byte contract. The Central Admin backend must produce
    // this exact string from these exact inputs, with no code shared from
    // here.
    expect(signature).toBe(SIGNATURE);
  });

  it('verifies the agreed signature', () => {
    const signature = SIGNATURE;

    const result = verifyAdminSignature({
      method: VECTOR.method,
      path: VECTOR.path,
      rawBody,
      signatureHeader: signature,
      timestampHeader: VECTOR.timestamp,
      requestId: VECTOR.requestId,
      actorRef: VECTOR.actorRef,
      secret: VECTOR.secret,
      now: new Date(Number(VECTOR.timestamp) * 1000),
    });

    expect(result).toEqual({ valid: true });
  });
});

describe('verifyAdminSignature', () => {
  const at = (timestamp: string) => new Date(Number(timestamp) * 1000);

  const sign = (
    input: {
      method: string;
      path: string;
      timestamp: string;
      requestId: string;
      actorRef: string;
      rawBody: Buffer | undefined;
    },
    secret = SECRET,
  ) =>
    `sha256=${createHmac('sha256', secret).update(adminSigningBase(input)).digest('hex')}`;

  const request = {
    method: 'POST',
    path: '/api/v1/integrations/admin-control/teams',
    timestamp: '1774000000',
    requestId: 'cmd-1',
    actorRef: 'admin-1',
    rawBody: Buffer.from('{"name":"Sales"}'),
  };

  const verify = (overrides: Record<string, unknown> = {}) =>
    verifyAdminSignature({
      method: request.method,
      path: request.path,
      rawBody: request.rawBody,
      signatureHeader: sign(request),
      timestampHeader: request.timestamp,
      requestId: request.requestId,
      actorRef: request.actorRef,
      secret: SECRET,
      now: at(request.timestamp),
      ...overrides,
    });

  it('accepts a correctly signed request', () => {
    expect(verify()).toEqual({ valid: true });
  });

  it('fails closed when no secret is configured', () => {
    // A deployment that forgot the secret must reject everything rather than
    // waving it through in silence.
    expect(verify({ secret: undefined })).toEqual({ valid: false, reason: 'NOT_CONFIGURED' });
  });

  it.each([
    ['signature', { signatureHeader: undefined }],
    ['timestamp', { timestampHeader: undefined }],
    ['request id', { requestId: undefined }],
    ['actor reference', { actorRef: undefined }],
  ])('refuses a request with no %s', (_label, overrides) => {
    expect(verify(overrides)).toEqual({ valid: false, reason: 'MISSING_HEADERS' });
  });

  it('refuses a malformed timestamp', () => {
    expect(verify({ timestampHeader: 'yesterday' })).toEqual({
      valid: false,
      reason: 'MALFORMED_TIMESTAMP',
    });
  });

  it('refuses a stale request', () => {
    // Six minutes late, against a five-minute window.
    expect(verify({ now: at(String(Number(request.timestamp) + 360)) })).toEqual({
      valid: false,
      reason: 'STALE_TIMESTAMP',
    });
  });

  it('refuses a request from the future', () => {
    // Symmetric, because a clock can be fast as easily as slow — and a captured
    // request dated forward would otherwise stay usable for as long as the
    // sender liked.
    expect(verify({ now: at(String(Number(request.timestamp) - 360)) })).toEqual({
      valid: false,
      reason: 'STALE_TIMESTAMP',
    });
  });

  it('accepts drift inside the window, in both directions', () => {
    expect(verify({ now: at(String(Number(request.timestamp) + 299)) })).toEqual({ valid: true });
    expect(verify({ now: at(String(Number(request.timestamp) - 299)) })).toEqual({ valid: true });
  });

  it('refuses a signature in the wrong shape', () => {
    expect(verify({ signatureHeader: 'deadbeef' })).toEqual({
      valid: false,
      reason: 'MALFORMED_SIGNATURE',
    });
    expect(verify({ signatureHeader: 'md5=deadbeef' })).toEqual({
      valid: false,
      reason: 'MALFORMED_SIGNATURE',
    });
  });

  it('refuses a signature made with a different secret', () => {
    expect(verify({ signatureHeader: sign(request, 'a-different-secret-of-sufficient-length') })).toEqual(
      { valid: false, reason: 'MISMATCH' },
    );
  });

  it.each([
    ['method', { method: 'PATCH' }],
    ['path', { path: '/api/v1/integrations/admin-control/territories' }],
    ['request id', { requestId: 'cmd-2' }],
    ['actor reference', { actorRef: 'admin-2' }],
  ])('refuses when the %s does not match what was signed', (_label, overrides) => {
    // Each of these is bound by the signature, so altering one in flight is a
    // forgery rather than a variation.
    expect(verify(overrides)).toEqual({ valid: false, reason: 'MISMATCH' });
  });

  it('refuses when the body does not match what was signed', () => {
    expect(verify({ rawBody: Buffer.from('{"name":"Somebody Else"}') })).toEqual({
      valid: false,
      reason: 'MISMATCH',
    });
  });

  it('refuses a body swapped for none, and the reverse', () => {
    expect(verify({ rawBody: undefined })).toEqual({ valid: false, reason: 'MISMATCH' });

    const bodyless = { ...request, rawBody: undefined };
    expect(
      verifyAdminSignature({
        method: bodyless.method,
        path: bodyless.path,
        rawBody: request.rawBody,
        signatureHeader: sign(bodyless),
        timestampHeader: bodyless.timestamp,
        requestId: bodyless.requestId,
        actorRef: bodyless.actorRef,
        secret: SECRET,
        now: at(bodyless.timestamp),
      }),
    ).toEqual({ valid: false, reason: 'MISMATCH' });
  });

  it('refuses a request id or actor carrying a newline', () => {
    // The delimiter attack: a value containing the separator could otherwise
    // produce the same signing base as a different request.
    expect(verify({ requestId: 'cmd-1\nPOST' })).toEqual({
      valid: false,
      reason: 'MALFORMED_REQUEST_ID',
    });
    expect(verify({ actorRef: 'admin\n/api/v1/x' })).toEqual({
      valid: false,
      reason: 'MALFORMED_ACTOR',
    });
  });

  it('never returns the expected signature or the secret', () => {
    const result = verify({ signatureHeader: 'sha256=00' });

    // The reason is a category, for our logs. A caller learns that the request
    // failed and nothing about how close they were.
    expect(JSON.stringify(result)).not.toContain(SECRET);
    expect(JSON.stringify(result)).not.toMatch(/[0-9a-f]{64}/);
  });
});
