import { randomBytes } from 'node:crypto';

/**
 * UUID version 7 — 48-bit big-endian Unix millisecond timestamp, then 74 bits
 * of randomness, with the version and variant bits set per RFC 9562.
 *
 * Implemented here rather than pulled from a package for two reasons: the
 * `uuid` package is ESM-only and does not load under Jest's CommonJS runtime,
 * and this mirrors the `uuidv7()` SQL function created in migration
 * 20260820090000_init, so ids generated by the application and by the database
 * have identical structure and sort together.
 *
 * Why v7 at all: random v4 keys scatter inserts across an index, causing page
 * splits and cache churn on high-write tables such as lead_activities. v7 keys
 * append to the right edge instead.
 *
 *   0                   1                   2                   3
 *   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 *  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *  |                       unix_ts_ms (48 bits)                    |
 *  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *  | ver(7)|              rand_a / rand_b (74 bits)                |
 *  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 */
export function uuidv7(now: number = Date.now()): string {
  const bytes = randomBytes(16);
  const timestamp = BigInt(now);

  // Bytes 0..5: the timestamp, most significant byte first.
  for (let i = 0; i < 6; i += 1) {
    bytes[i] = Number((timestamp >> BigInt(8 * (5 - i))) & 0xffn);
  }

  // Byte 6 high nibble: version 7. Low nibble stays random.
  bytes[6] = ((bytes[6] as number) & 0x0f) | 0x70;

  // Byte 8 top two bits: RFC 9562 variant (10xx).
  bytes[8] = ((bytes[8] as number) & 0x3f) | 0x80;

  const hex = bytes.toString('hex');
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join('-');
}
